version: '2'
services:
    nginx:
        image: nginx:latest
        container_name: NGINX
        ports:
            - "80:80"
        volumes:
            - ./logs:/var/log/nginx
            - ../:/var/www/html
            - ./:/etc/nginx/conf.d
        links:
          - fpm
    fpm:
        build:
          context: .
          dockerfile: ./PHP/Dockerfile
        container_name: FPM
        volumes:
          - ../:/var/www/html
        expose:
          - 9000
    mysql:
        image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: kolya
          MYSQL_PASSWORD: kolya
          MYSQL_DATABASE: kolya
        ports:
          - '3306:3306'